theme = "onedark"
[editor]
line-number = "relative"
cursorline = true
true-color = true
mouse = false
undercurl = true
color-modes = true
end-of-line-diagnostics = "hint"

gutters = ["diagnostics", "spacer", "diff", "line-numbers", "spacer", "spacer"]

[editor.statusline]
mode.normal = ""
mode.insert = "INSERT"
mode.select = "SELECT"
right = ["diagnostics", "version-control", "position", "file-encoding"]

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.indent-guides]
render = false
charactor = "╎"
#skip-levels = 1

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.inline-diagnostics]

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
tab = "→"

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false
git-global = false

[keys.normal]
y = "yank_joined_to_clipboard"

